import Head from 'next/head';
import { Inter } from '@next/font/google';
import Headers from '../../components/Headers';
import Navbar from '../../components/NavBar';
import CategorySection from '../../section/CategorySection';
import TitleCategory from '../../components/TitleCategory';
import FooterSection from '../../section/FootersSection';
import ItemDetail from '../../components/ItemDetail';

type itemProps = {};

const product = (props: itemProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" relative bg-background">
        <div className="hidden md:block gradient-02 inset-01 absolute w-[50%]" />
        <Headers />
        <Navbar />
        <div className="hidden md:block gradient-02 inset-0 absolute w-[50%]" />
        <div className="py-20">
          <ItemDetail />
        </div>
        <FooterSection />
      </main>
    </>
  );
};

export default product;
