import Head from 'next/head';
import { Inter } from '@next/font/google';
import Headers from '../../components/Headers';
import Navbar from '../../components/NavBar';
import CategorySection from '../../section/CategorySection';
import TitleCategory from '../../components/TitleCategory';
import FooterSection from '../../section/FootersSection';
import ItemDetail from '../../components/ItemDetail';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { ApiProduct } from '../../utils/API';

type itemProps = {};

const product = (props: itemProps) => {
  const router = useRouter();
  const [loading, setLoading] = useState<boolean>(true);
  const [singleProduct, setSingleProduct] = useState<any>();
  const getDataProduct = async (id: any) => {
    setLoading(true);
    const response = await ApiProduct.getSingleProduct(id);
    setSingleProduct(response);
    setLoading(false);
  };
  useEffect(() => {
    if (!router.isReady) {
      setLoading(true);
    }
    if (router.isReady) {
      getDataProduct(router.query.product);
    }
    // codes using router.query
  }, [router.isReady]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" relative bg-background">
        <Headers />
        <Navbar />

        <div className="py-20">
          {!loading && <ItemDetail data={singleProduct} />}
        </div>
        <FooterSection />
      </main>
    </>
  );
};

export default product;
