import Head from 'next/head';
import { Inter } from '@next/font/google';
import Headers from '../components/Headers';
import Navbar from '../components/NavBar';
import CategorySection from '../section/CategorySection';
import TitleCategory from '../components/TitleCategory';
import Catalog from '../section/Catalog';
import InfoSection from '../section/InfoSection';
import FooterSection from '../section/FootersSection';
import CategoryItem from '../components/CategoryItem';
import { asyncSetAllProduct } from '../states/Product/action';
import { useAppDispatch } from '../states';
import Link from 'next/link';

type registerProps = {};

const register = (props: registerProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" relative">
        <div className="hidden md:block gradient-02 inset-01 absolute w-[50%]" />
        <Headers />
        <div className="flex w-full py-[200px] justify-center">
          <div className="bg-white p-6 rounded-lg w-[400px]">
            <h2 className="text-lg text-jingga font-extrabold mb-4">
              Register
            </h2>
            <div className="mb-4">
              <label className="block text-gray-700 font-medium mb-2">
                Email
              </label>
              <input
                className="border border-gray-400 p-2 rounded-lg w-full"
                type="email"
                id="email"
                name="email"
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 font-medium mb-2">
                Username
              </label>
              <input
                className="border border-gray-400 p-2 rounded-lg w-full"
                type="username"
                id="username"
                name="username"
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 font-medium mb-2">
                Password
              </label>
              <input
                className="border border-gray-400 p-2 rounded-lg w-full"
                type="password"
                id="password"
                name="password"
              />
            </div>
            <Link href="/login">
              <label className=" hover:underline block text-jingga hover:cursor-pointer font-medium mb-2">
                Login
              </label>
            </Link>
            <button className="bg-jingga text-white py-2 px-4 rounded-lg hover:bg-indigo-600">
              Register
            </button>
          </div>
        </div>
        <div className="py-12">
          <InfoSection />
        </div>
        <FooterSection />
      </main>
    </>
  );
};

export default register;
